# Generated by Django 3.2.13 on 2022-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
