# Generated by Django 3.2.13 on 2022-05-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_cover_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_page',
        ),
    ]
